import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import { Inter } from "@next/font/google"
// import styles from "@/styles/Home.module.css"
import styles from "../styles/CheckinForm.module.css"
const inter = Inter({ subsets: ["latin"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Form Registration</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,300;0,400;1,300;1,400&display=swap"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Link href="mycheckin">
            <h1>My checkin</h1>
          </Link>
        </div>
        <div className={styles.center}>
          <Link href="checkin">
            <h1>Checkin Form</h1>
          </Link>
        </div>
      </main>
    </>
  )
}
